### ISSUE TITLE
Add GPG keys to app phase 1

### ISSUE THREAD

**Issue by JonasWijne** [threefoldtech/threefold_connect#409]
We need GPG Keys in the app so that we can use these to sign certain things (eg. git commits for gitea).

### Todo's:

- [x] generate GPG keys on app 
- [ ] save GPG public key on login.threefold.me api eg. https://login.threefold.me/api/users/wijnejonas.3bot
- [ ] make possible to download/copy private and public GPG key (maby with login scope)
- [ ]  add documentation on how to use this flow
- [ ] add example on how to validate something that's signed with the private GPG key based on the login.threefold.me api
- [ ] complete ticket phase 2 https://github.com/threefoldtech/threefold_connect/issues/410

### Things to keep in mind:

- multiple GPG keypairs should be possible 

### Phase 2

Need to have a "virtual smartcard" (think of yubikey) that can sign/encrypt on your phone so that we can remove the Private key part of this flow
https://frankmorgner.github.io/vsmartcard/index.html

**Comment by LennertDefauw1** [comment]
https://user-images.githubusercontent.com/43674202/161567170-135e6d81-43cb-46f6-83e0-9b48dcd42864.mp4



Current implementation in flutter:


We are using openpgp to generate new GPG keys. These keys will be managed inside the app. It is possible to create more than 1 key. Keys are being stored in PKID:

{
name: 'name',
email: 'email',
pk: 'PUBLIC KEY GPG',
sk: 'SECRET KEY GPG'
}
